fos_user:
    db_driver: orm
    firewall_name: main
    user_class: App\Entity\User

    from_email:
        address: "no-reply@tudominio.com"
        sender_name: "Symfony Legacy App"

    service:
        mailer: fos_user.mailer.twig_swift
