swiftmailer:
    transport: smtp
    host: mail.datafact.com.ec
    username: ressetingrequest@datafact.com.ec
    password: '$g?KurdT!RzvS2LR'
    port: 465
    encryption: ssl
    auth_mode: login
    stream_options:
        ssl:
            allow_self_signed: true
            verify_peer: false
            verify_peer_name: false

